version: '3'

services:

  playground-mongo:
    container_name: playground-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - playground-data:/data/db

  playground-api:
    build: ./playground-api
    container_name: playground-api
    restart: always
    ports:
      - '8081:8080'
    links:
      - playground-mongo
    volumes:
      - ./playground-api:/app

  playground-frontend:
    build: ./playground-frontend
    container_name: playground-frontend
    restart: always
    ports:
      - 8082:3000
    links:
      - playground-api
    volumes:
      - ./playground-frontend:/app


volumes:
  playground-data: